//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bd_Curs.Localization {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bd_Curs.Localization.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wrong login or password.
        /// </summary>
        public static string AuthorizationError {
            get {
                return ResourceManager.GetString("AuthorizationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Auto increment.
        /// </summary>
        public static string AutoIncrement {
            get {
                return ResourceManager.GetString("AutoIncrement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cascade update tables.
        /// </summary>
        public static string CascadeCheckBox {
            get {
                return ResourceManager.GetString("CascadeCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Column.
        /// </summary>
        public static string ColumnLabel {
            get {
                return ResourceManager.GetString("ColumnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Conditions.
        /// </summary>
        public static string Condition {
            get {
                return ResourceManager.GetString("Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connect to database.
        /// </summary>
        public static string ConnectButtonText {
            get {
                return ResourceManager.GetString("ConnectButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Database.
        /// </summary>
        public static string ConnectionStatusDB {
            get {
                return ResourceManager.GetString("ConnectionStatusDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wasn&apos;t Connected.
        /// </summary>
        public static string ConnectionStatusDis {
            get {
                return ResourceManager.GetString("ConnectionStatusDis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Server.
        /// </summary>
        public static string ConnectionStatusServer {
            get {
                return ResourceManager.GetString("ConnectionStatusServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Connect To Server.
        /// </summary>
        public static string ConnectServerButton {
            get {
                return ResourceManager.GetString("ConnectServerButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Count of fields.
        /// </summary>
        public static string CountOfFields {
            get {
                return ResourceManager.GetString("CountOfFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create сonstraint.
        /// </summary>
        public static string CreateConstraint {
            get {
                return ResourceManager.GetString("CreateConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create database.
        /// </summary>
        public static string CreateDBButton {
            get {
                return ResourceManager.GetString("CreateDBButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter database name.
        /// </summary>
        public static string CreateDBNameText {
            get {
                return ResourceManager.GetString("CreateDBNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You want to create Database?.
        /// </summary>
        public static string CreateDbQue {
            get {
                return ResourceManager.GetString("CreateDbQue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create new field.
        /// </summary>
        public static string CreateNewField {
            get {
                return ResourceManager.GetString("CreateNewField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create relation.
        /// </summary>
        public static string CreateRelationButton {
            get {
                return ResourceManager.GetString("CreateRelationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create table.
        /// </summary>
        public static string CreateTable {
            get {
                return ResourceManager.GetString("CreateTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DatabaseName.
        /// </summary>
        public static string DataBaselabel {
            get {
                return ResourceManager.GetString("DataBaselabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Database constructor.
        /// </summary>
        public static string DbConstructor {
            get {
                return ResourceManager.GetString("DbConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DatabaseCreate.
        /// </summary>
        public static string DbcreateUpper {
            get {
                return ResourceManager.GetString("DbcreateUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Database diagram.
        /// </summary>
        public static string DbDiagram {
            get {
                return ResourceManager.GetString("DbDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string DefaultErrorMessageUpper {
            get {
                return ResourceManager.GetString("DefaultErrorMessageUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete field.
        /// </summary>
        public static string DeleteField {
            get {
                return ResourceManager.GetString("DeleteField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete form.
        /// </summary>
        public static string DeleteFormName {
            get {
                return ResourceManager.GetString("DeleteFormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disconnect from database.
        /// </summary>
        public static string DisConnectButtonText {
            get {
                return ResourceManager.GetString("DisConnectButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Don&apos;t connected.
        /// </summary>
        public static string DontConnected {
            get {
                return ResourceManager.GetString("DontConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter DataBase Name.
        /// </summary>
        public static string EnterDBname {
            get {
                return ResourceManager.GetString("EnterDBname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Field name.
        /// </summary>
        public static string FieldName {
            get {
                return ResourceManager.GetString("FieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Field type.
        /// </summary>
        public static string FieldType {
            get {
                return ResourceManager.GetString("FieldType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Insert.
        /// </summary>
        public static string Insert {
            get {
                return ResourceManager.GetString("Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Insert form.
        /// </summary>
        public static string InsertFormName {
            get {
                return ResourceManager.GetString("InsertFormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New сondition.
        /// </summary>
        public static string NewCondition {
            get {
                return ResourceManager.GetString("NewCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to connect to database.
        /// </summary>
        public static string NotConnectToDB {
            get {
                return ResourceManager.GetString("NotConnectToDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to disconnect from database.
        /// </summary>
        public static string NotDisconnectFromDB {
            get {
                return ResourceManager.GetString("NotDisconnectFromDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на NOT NULL please fill in the field.
        /// </summary>
        public static string NotNullMessage {
            get {
                return ResourceManager.GetString("NotNullMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Database name must not contain spaces!.
        /// </summary>
        public static string NotSpaces {
            get {
                return ResourceManager.GetString("NotSpaces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Nullable.
        /// </summary>
        public static string Nullable {
            get {
                return ResourceManager.GetString("Nullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Primary key.
        /// </summary>
        public static string Primary {
            get {
                return ResourceManager.GetString("Primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An error occurred while executing the request.
        /// </summary>
        public static string QueryException {
            get {
                return ResourceManager.GetString("QueryException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Query already in progress please wait.
        /// </summary>
        public static string QueryInProgress {
            get {
                return ResourceManager.GetString("QueryInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Relation.
        /// </summary>
        public static string RelationLabel {
            get {
                return ResourceManager.GetString("RelationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove all conditions.
        /// </summary>
        public static string RemoveAllConditions {
            get {
                return ResourceManager.GetString("RemoveAllConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Selected table.
        /// </summary>
        public static string Selectedtable {
            get {
                return ResourceManager.GetString("Selectedtable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select form.
        /// </summary>
        public static string SelectFormName {
            get {
                return ResourceManager.GetString("SelectFormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Server Adress.
        /// </summary>
        public static string ServerNamelabel {
            get {
                return ResourceManager.GetString("ServerNamelabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Symbols count.
        /// </summary>
        public static string SymbolsCount {
            get {
                return ResourceManager.GetString("SymbolsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tables:.
        /// </summary>
        public static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter table name.
        /// </summary>
        public static string Table_Name_Default {
            get {
                return ResourceManager.GetString("Table_Name_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Table info.
        /// </summary>
        public static string TableInfo {
            get {
                return ResourceManager.GetString("TableInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Table.
        /// </summary>
        public static string TableLabel {
            get {
                return ResourceManager.GetString("TableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на An error occurred while displaying the table.
        /// </summary>
        public static string TableSqlException {
            get {
                return ResourceManager.GetString("TableSqlException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Time of query.
        /// </summary>
        public static string TimeOfQuerylabel {
            get {
                return ResourceManager.GetString("TimeOfQuerylabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose a database.
        /// </summary>
        public static string TooltipDbName {
            get {
                return ResourceManager.GetString("TooltipDbName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter your server adress.
        /// </summary>
        public static string TooltipServerName {
            get {
                return ResourceManager.GetString("TooltipServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type of data.
        /// </summary>
        public static string TypeOfData {
            get {
                return ResourceManager.GetString("TypeOfData", resourceCulture);
            }
        }
    }
}
